Models/Actor.cs
using csharp_boolflix.Models;

public class Actor
{
    public int Id { get; set; }
    public string Name { get; set; }
    public string Surname { get; set; }
    public string Fullname { get { return Name + " " + Surname; } }


    public List<MediaInfo>? MediaInfos { get; set; }
}

Models/Feature.cs
using csharp_boolflix.Models;

public class Feature
{
    public int Id { get; set; }
    public string Name { get; set; }

    public List<MediaInfo>? MediaInfos { get; set; }
}

Controllers/ActorController.cs
using csharp_boolflix.Context;
using Microsoft.AspNetCore.Mvc;

namespace csharp_boolflix.Controllers
{
    public class ActorController : Controller
    {
        BoolflixDbContext db;
        public ActorController()
        {
            db = new();
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Store(Actor model)
        {
            if (!ModelState.IsValid)
            {
                return View("Create", model);
            }

            db.Add(model);
            db.SaveChanges();

            return RedirectToAction("Actors", "Editor");
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            Actor actor = db.Actors.Find(id);

            if (actor == null)
            {
                return NotFound("Non è stato possibile trovare l'attore da modificare");
            }
            else
            {
                return View(actor);
            }

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(int id, Actor model)
        {

            if (!ModelState.IsValid)
            {
                return View("Edit", model);
            }

            Actor actor = db.Actors.Find(id);

            actor.Name = model.Name;
            actor.Surname = model.Surname;

            db.SaveChanges();

            return RedirectToAction("Actors", "Editor");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int id)
        {
            Actor actor = db.Actors.Find(id);

            if (actor == null)
            {
                return NotFound();
            }
            else
            {
                db.Actors.Remove(actor);
                db.SaveChanges();

                return RedirectToAction("Actors", "Editor");
            }

        }
    }
}

Controllers/EditorController.cs
using csharp_boolflix.Context;
using Microsoft.AspNetCore.Mvc;

namespace csharp_boolflix.Controllers
{
    public class EditorController : Controller
    {
        BoolflixDbContext db;
        public EditorController()
        {
            db = new();
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Films()
        {
            return View(db.Films.ToList());
        }
        public IActionResult TvSeries()
        {
            return View(db.TvSeries.ToList());
        }
        public IActionResult Actors()
        {
            return View(db.Actors.ToList());
        }
        public IActionResult Genres()
        {
            return View(db.Genres.ToList());
        }
        public IActionResult Features()
        {
            return View(db.Features.ToList());
        }
    }
}

Controllers/EpisodeController.cs
using csharp_boolflix.Context;
using csharp_boolflix.Models;
using Microsoft.AspNetCore.Mvc;

namespace csharp_boolflix.Controllers
{
    public class EpisodeController : Controller
    {
        BoolflixDbContext db;
        public EpisodeController()
        {
            db = new();
        }

        public IActionResult Create(int id)
        {
            TvSerie tvSerie = db.TvSeries.Find(id);

            SupportClass supportClass = new()
            {
                TvSerie = tvSerie,
                tvSerieId = id
            };
            

            return View(supportClass);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Store(SupportClass model)
        {

            if (!ModelState.IsValid)
            {
                model.Episode.TvSeries = db.TvSeries.Find(model.tvSerieId);
                return View("Create", model);
            }

            model.Episode.TvSeries = db.TvSeries.Find(model.tvSerieId);

            db.Add(model.Episode);
            db.SaveChanges();

            return RedirectToAction("TvSeries", "Editor");
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            Actor actor = db.Actors.Find(id);

            if (actor == null)
            {
                return NotFound("Non è stato possibile trovare l'attore da modificare");
            }
            else
            {
                return View(actor);
            }

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(int id, Actor model)
        {

            if (!ModelState.IsValid)
            {
                return View("Edit", model);
            }

            Actor actor = db.Actors.Find(id);

            actor.Name = model.Name;
            actor.Surname = model.Surname;

            db.SaveChanges();

            return RedirectToAction("Actors", "Editor");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int id)
        {
            Actor actor = db.Actors.Find(id);

            if (actor == null)
            {
                return NotFound();
            }
            else
            {
                db.Actors.Remove(actor);
                db.SaveChanges();

                return RedirectToAction("Actors", "Editor");
            }

        }
    }
}

Controllers/FeatureController.cs
using Microsoft.AspNetCore.Mvc;

namespace csharp_boolflix.Controllers
{
    public class FeatureController : Controller
    {
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Store(Feature feature)
        {
            return View();
        }
    }
}

Controllers/FilmController.cs
using csharp_boolflix.Context;
using csharp_boolflix.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace csharp_boolflix.Controllers
{
    public class FilmController : Controller
    {
        BoolflixDbContext db;
        public FilmController()
        {
            db = new();
        }

        public IActionResult Create()
        {
            SupportClass supportClass = new() 
            {
                Actors = db.Actors.ToList(),
                Genres = db.Genres.ToList(),
                Features = db.Features.ToList(),
            };
            return View(supportClass);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Store(SupportClass model)
        {
            if (!ModelState.IsValid)
            {
                model.Actors = db.Actors.ToList();
                model.Genres = db.Genres.ToList();
                model.Features = db.Features.ToList();
                return View("Create", model);
            }

            foreach (int Id in model.SelectedActors)
            {
                model.Film.MediaInfo.Cast.Add(db.Actors.Find(Id));
            }
            foreach (int Id in model.SelectedGenres)
            {
                model.Film.MediaInfo.Genres.Add(db.Genres.Find(Id));
            }
            foreach (int Id in model.SelectedFeatures)
            {
                model.Film.MediaInfo.Features.Add(db.Features.Find(Id));
            }

            db.Add(model.Film);
            db.Add(model.Film.MediaInfo);
            db.SaveChanges();

            return RedirectToAction("Films", "Editor");
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            Film film = db.Films.Include("MediaInfo").Where(f => f.Id == id).First();
            MediaInfo mediaInfo = db.MediaInfos.Include("Cast").Include("Genres").Include("Features").Where(m => m.FilmId == id).First();

            if (film == null)
            {
                return NotFound("Non è stato possibile trovare il film da modificare");
            }
            else
            {
                SupportClass supportClass = new()
                {
                    Film = film,
                    Actors = db.Actors.ToList(),
                    Genres = db.Genres.ToList(),
                    Features = db.Features.ToList(),
                };

                foreach (Actor actor in mediaInfo.Cast)
                {
                    supportClass.SelectedActors.Add(actor.Id);
                }
                foreach (Genre genre in mediaInfo.Genres)
                {
                    supportClass.SelectedGenres.Add(genre.Id);
                }
                foreach (Feature feature in mediaInfo.Features)
                {
                    supportClass.SelectedFeatures.Add(feature.Id);
                }

                return View(supportClass);
            }

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(int id, SupportClass model)
        {

            if (!ModelState.IsValid)
            {
                model.Actors = db.Actors.ToList();
                model.Genres = db.Genres.ToList();
                model.Features = db.Features.ToList();
                return View("Edit", model);
            }

            MediaInfo mediaInfo = db.MediaInfos.Include("Film").Include("Cast").Include("Genres").Include("Features").Where(m => m.FilmId == id).First();

            mediaInfo.Film.Duration = model.Film.Duration;
            mediaInfo.Film.Description = model.Film.Description;
            mediaInfo.Film.Title = model.Film.Title;
            foreach (int Id in model.SelectedActors)
            {
                mediaInfo.Cast.Add(db.Actors.Find(Id));
            }
            foreach (int Id in model.SelectedGenres)
            {
                mediaInfo.Genres.Add(db.Genres.Find(Id));
            }
            foreach (int Id in model.SelectedFeatures)
            {
                 mediaInfo.Features.Add(db.Features.Find(Id));
            }


            db.SaveChanges();

            return RedirectToAction("Films", "Editor");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int id)
        {
            Film film = db.Films.Find(id);
            MediaInfo mediaInfo = db.MediaInfos.Where(m => m.FilmId == id).First();

            if (mediaInfo == null)
            {
                return NotFound();
            }
            else
            {
                db.Films.Remove(film);
                db.MediaInfos.Remove(mediaInfo);
                db.SaveChanges();

                return RedirectToAction("Films", "Editor");
            }

        }
    }
}

Controllers/GenreController.cs
using csharp_boolflix.Context;
using Microsoft.AspNetCore.Mvc;

namespace csharp_boolflix.Controllers
{
    public class GenreController : Controller
    {
        BoolflixDbContext db;
        public GenreController()
        {
            db = new();
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Store(Genre model)
        {
            if (!ModelState.IsValid)
            {
                return View("Create", model);
            }

            db.Add(model);
            db.SaveChanges();

            return RedirectToAction("Genres", "Editor");
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            Genre genre = db.Genres.Find(id);

            if (genre == null)
            {
                return NotFound("Non è stato possibile trovare il genere da modificare");
            }
            else
            {
                return View(genre);
            }

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(int id, Genre model)
        {

            if (!ModelState.IsValid)
            {
                return View("Edit", model);
            }

            Genre genre = db.Genres.Find(id);

            genre.Name = model.Name;

            db.SaveChanges();

            return RedirectToAction("Genres", "Editor");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int id)
        {
            Genre genre = db.Genres.Find(id);

            if (genre == null)
            {
                return NotFound();
            }
            else
            {
                db.Genres.Remove(genre);
                db.SaveChanges();

                return RedirectToAction("Genres", "Editor");
            }

        }
    }
}

Controllers/TvSerieController.cs
using csharp_boolflix.Context;
using csharp_boolflix.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace csharp_boolflix.Controllers
{
    public class TvSerieController : Controller
    {
        BoolflixDbContext db;
        public TvSerieController()
        {
            db = new();
        }

        public IActionResult Create()
        {
            SupportClass supportClass = new()
            {
                Actors = db.Actors.ToList(),
                Genres = db.Genres.ToList(),
                Features = db.Features.ToList(),
            };
            return View(supportClass);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Store(SupportClass model)
        {
            if (!ModelState.IsValid)
            {
                model.Actors = db.Actors.ToList();
                model.Genres = db.Genres.ToList();
                model.Features = db.Features.ToList();
                return View("Create", model);
            }

            foreach (int Id in model.SelectedActors)
            {
                model.TvSerie.MediaInfo.Cast.Add(db.Actors.Find(Id));
            }
            foreach (int Id in model.SelectedGenres)
            {
                model.TvSerie.MediaInfo.Genres.Add(db.Genres.Find(Id));
            }
            foreach (int Id in model.SelectedFeatures)
            {
                model.TvSerie.MediaInfo.Features.Add(db.Features.Find(Id));
            }

            db.Add(model.TvSerie);
            db.Add(model.TvSerie.MediaInfo);
            db.SaveChanges();

            return RedirectToAction("TvSeries", "Editor");
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            TvSerie tvSerie = db.TvSeries.Include("MediaInfo").Where(t => t.Id == id).First();
            MediaInfo mediaInfo = db.MediaInfos.Include("Cast").Include("Genres").Include("Features").Where(m => m.TvSeriesId == id).First();

            if (tvSerie == null)
            {
                return NotFound("Non è stato possibile trovare la serie TV da modificare");
            }
            else
            {
                SupportClass supportClass = new()
                {
                    TvSerie = tvSerie,
                    Actors = db.Actors.ToList(),
                    Genres = db.Genres.ToList(),
                    Features = db.Features.ToList(),
                };

                foreach (Actor actor in mediaInfo.Cast)
                {
                    supportClass.SelectedActors.Add(actor.Id);
                }
                foreach (Genre genre in mediaInfo.Genres)
                {
                    supportClass.SelectedGenres.Add(genre.Id);
                }
                foreach (Feature feature in mediaInfo.Features)
                {
                    supportClass.SelectedFeatures.Add(feature.Id);
                }

                return View(supportClass);
            }

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(int id, SupportClass model)
        {

            if (!ModelState.IsValid)
            {
                model.Actors = db.Actors.ToList();
                model.Genres = db.Genres.ToList();
                model.Features = db.Features.ToList();
                return View("Edit", model);
            }

            MediaInfo mediaInfo = db.MediaInfos.Include("TvSeries").Include("Cast").Include("Genres").Include("Features").Where(m => m.TvSeriesId == id).First();

            mediaInfo.TvSeries.SeasonsCount = model.TvSerie.SeasonsCount;
            mediaInfo.TvSeries.Description = model.TvSerie.Description;
            mediaInfo.TvSeries.Title = model.TvSerie.Title;
            foreach (int Id in model.SelectedActors)
            {
                mediaInfo.Cast.Add(db.Actors.Find(Id));
            }
            foreach (int Id in model.SelectedGenres)
            {
                mediaInfo.Genres.Add(db.Genres.Find(Id));
            }
            foreach (int Id in model.SelectedFeatures)
            {
                mediaInfo.Features.Add(db.Features.Find(Id));
            }


            db.SaveChanges();

            return RedirectToAction("TvSeries", "Editor");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int id)
        {
            TvSerie tvSerie = db.TvSeries.Find(id);
            MediaInfo mediaInfo = db.MediaInfos.Where(m => m.TvSeriesId == id).First();

            if (mediaInfo == null)
            {
                return NotFound();
            }
            else
            {
                db.TvSeries.Remove(tvSerie);
                db.MediaInfos.Remove(mediaInfo);
                db.SaveChanges();

                return RedirectToAction("TvSeries", "Editor");
            }

        }
    }
}

Views/Editor/Actors.cshtml
@model List<Actor>;

@{
    ViewData["Title"] = "Attori";

    Layout = "_EditorLayout";
}

<a asp-action="Create" asp-controller="Actor">Crea nuovo</a>
<h2>Lista attori</h2>

<hr />

@if(Model.Count == 0){
    <div class="alert alert-primary" role="alert">
        Non sono presenti attori.
    </div>
}
else
{
    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Nome</th>
                <th scope="col">Cognome</th>
                <th scope="col">Azioni</th>
            </tr>
        </thead>
        <tbody>
            @foreach (Actor actor in Model)
            {
                <tr>
                    <th scope="row">@actor.Id</th>
                    <td>@actor.Name</td>
                    <td>@actor.Surname</td>
                    <td>
                        <a href="@Url.Action("Edit", "Actor", new {id = actor.Id})" class="btn btn-primary">Modifica</a>
                        <form asp-controller="Actor" asp-action="Delete" asp-route-id="@actor.Id" method="post">
                            @Html.AntiForgeryToken()
                            <button type="submit" class="btn btn-danger">Elimina</button>
                        </form>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}

Views/Editor/Features.cshtml
@model List<Feature>;

@{
    ViewData["Title"] = "Caratteristiche";

    Layout = "_EditorLayout";
}

<a asp-action="Create" asp-controller="Feature">Crea nuova</a>
<h2>Lista caratteristiche</h2>

<hr />

@if(Model.Count == 0){
    <div class="alert alert-primary" role="alert">
        Non sono presenti caratteristiche.
    </div>
}
else
{
    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Nome</th>
                <th scope="col">Azioni</th>
            </tr>
        </thead>
        <tbody>
            @foreach (Feature feature in Model)
            {
                <tr>
                    <th scope="row">@feature.Id</th>
                    <td>@feature.Name</td>
                    <td>
                        <a href="@Url.Action("Edit", "Feature", new {id = feature.Id})" class="btn btn-primary">Modifica</a>
                        <form asp-controller="Feature" asp-action="Delete" asp-route-id="@feature.Id" method="post">
                            @Html.AntiForgeryToken()
                            <button type="submit" class="btn btn-danger">Elimina</button>
                        </form>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}

Views/Editor/Films.cshtml
@model List<Film>;

@{
    ViewData["Title"] = "Film";

    Layout = "_EditorLayout";
}

<a asp-action="Create" asp-controller="Film">Crea nuovo</a>
<h2>Lista film</h2>

<hr />

@if (Model.Count == 0)
{
    <div class="alert alert-primary" role="alert">
        Non sono presenti film.
    </div>
}
else
{
    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Titolo</th>
                <th scope="col">Durata</th>
                <th scope="col">Descrizione</th>
                <th scope="col">Azioni</th>
            </tr>
        </thead>
        <tbody>
            @foreach (Film film in Model)
            {
                <tr>
                    <th scope="row">@film.Id</th>
                    <td>@film.Title</td>
                    <td>@film.Duration</td>
                    <td>@film.Description</td>
                    <td>
                        <a href="@Url.Action("Edit", "Film", new {id = film.Id})" class="btn btn-primary">Modifica</a>
                        <form asp-controller="Film" asp-action="Delete" asp-route-id="@film.Id" method="post">
                            @Html.AntiForgeryToken()
                            <button type="submit" class="btn btn-danger">Elimina</button>
                        </form>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}

Views/Editor/Genres.cshtml
@model List<Genre>;

@{
    ViewData["Title"] = "Generi";

    Layout = "_EditorLayout";
}

<a asp-action="Create" asp-controller="Genre">Crea nuovo</a>
<h2>Lista generi</h2>

<hr />

@if (Model.Count == 0)
{
    <div class="alert alert-primary" role="alert">
        Non sono presenti generi.
    </div>
}
else
{
    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Nome</th>
                <th scope="col">Azioni</th>
            </tr>
        </thead>
        <tbody>
            @foreach (Genre genre in Model)
            {
                <tr>
                    <th scope="row">@genre.Id</th>
                    <td>@genre.Name</td>
                    <td>
                        <a href="@Url.Action("Edit", "Genre", new {id = genre.Id})" class="btn btn-primary">Modifica</a>
                        <form asp-controller="Genre" asp-action="Delete" asp-route-id="@genre.Id" method="post">
                            @Html.AntiForgeryToken()
                            <button type="submit" class="btn btn-danger">Elimina</button>
                        </form>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}

Views/Editor/Index.cshtml
@{
    ViewData["Title"] = "Home Page";

    Layout = "_EditorLayout";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Editor/TvSeries.cshtml
@model List<TvSerie>;

@{
    ViewData["Title"] = "Serie TV";

    Layout = "_EditorLayout";
}

<a asp-action="Create" asp-controller="TvSerie">Crea nuova serie Tv</a>
<h2>Lista Serie TV</h2>

<hr />

@if (Model.Count == 0)
{
    <div class="alert alert-primary" role="alert">
        Non sono presenti serie TV.
    </div>
}
else
{
    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Titolo</th>
                <th scope="col">Numero di stagioni</th>
                <th scope="col">Descrizione</th>
                <th scope="col">Azioni</th>
            </tr>
        </thead>
        <tbody>
            @foreach (TvSerie tvSerie in Model)
            {
                <tr>
                    <th scope="row">@tvSerie.Id</th>
                    <td>@tvSerie.Title</td>
                    <td>@tvSerie.SeasonsCount</td>
                    <td>@tvSerie.Description</td>
                    <td>
                        <a href="@Url.Action("Edit", "TvSerie", new {id = tvSerie.Id})" class="btn btn-primary">Modifica</a>
                        <form asp-controller="TvSerie" asp-action="Delete" asp-route-id="@tvSerie.Id" method="post">
                            @Html.AntiForgeryToken()
                            <button type="submit" class="btn btn-danger">Elimina</button>
                        </form>
                        <a href="@Url.Action("Create", "Episode", new {id = tvSerie.Id})" class="btn btn-dark">Aggiungi episodio</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}